name: ZeroPath AI Scan
on:
    pull_request:
        types: [opened, reopened, synchronize]
branches:
    - main

jobs:g
    scan:
        name: "Run ZeroPath Scan"
        runs-on: ubuntu-latest
        timeout-minutes: 10
        if: ${{ !contains(github.actor, '[bot]') && !contains(github.event.pull_request.user.login, '[bot]')}}
        permissions:
            pull-requests: write
        security-events: write
        statuses: write
        contents: write
        issues: write
        steps:
            - name: Run ZeroPath Scan
        uses: zeropathai/action@main
        with:
        zeropath-token: ${{ secrets.ZEROPATH_API_TOKEN }}
        zeropath-api-url: ${{ vars.ZEROPATH_API_URL }}
        pull-url: ${{ github.event.pull_request.html_url }}